// <auto-generated />
using DotNet8WebAPI.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet8WebAPI.Migrations
{
    [DbContext(typeof(AdvisorDbContext))]
    [Migration("20250326162551_d8webapi-migration")]
    partial class d8webapimigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet8WebAPI.Model.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Shubhang",
                            IsActive = true,
                            LastName = "Sharma"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ram",
                            IsActive = true,
                            LastName = "Pratap"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Shreya",
                            IsActive = true,
                            LastName = "Sharma"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Dewang",
                            IsActive = true,
                            LastName = "Parashar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
